Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2023-05, with the labels that each got.

#144 Create Flatpak package
  flatpak/OpenAndroidInstaller.png
  flatpak/generated-poetry-sources.json
  flatpak/org.openandroidinstaller.OpenAndroidInstaller.appdata.xml
  flatpak/org.openandroidinstaller.OpenAndroidInstaller.desktop
  flatpak/org.openandroidinstaller.OpenAndroidInstaller.png
  org.openandroidinstaller.OpenAndroidInstaller.json
  org.openandroidinstaller.OpenAndroidInstaller.yml
Labels: enhancement

#139 Improve the addons installer progress bars and fix issues
  openandroidinstaller/app_state.py
  openandroidinstaller/tooling.py
  openandroidinstaller/views/install_addons_view.py
Labels: bug, enhancement

#140 Support for Samsung Galaxy Grand Prime VE
  README.md
  openandroidinstaller/assets/configs/grandprimevelte.yaml
Labels: device

#168 add a5 2017
  openandroidinstaller/assets/configs/a5y17lte.yaml
Labels: device
