Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2023-12, with the labels that each got.

#362 add model names
  README.md
Labels: documentation

#365 add Oneplus3 support
  README.md
  openandroidinstaller/assets/configs/oneplus3.yaml
Labels: device

#400 Fix installer crashes when sideloading progress goes over 100%
  openandroidinstaller/widgets.py
Labels: bug
