Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2023-08, with the labels that each got.

#197 Actions update
  .github/workflows/build-release.yml
  .github/workflows/manual-build.yml
Labels: enhancement

#218 [SPLIT] OrangeFox support
  README.md
  openandroidinstaller/assets/imgs/ofox.png
  openandroidinstaller/installer_config.py
  openandroidinstaller/tooling.py
  openandroidinstaller/utils.py
  openandroidinstaller/views/install_addons_view.py
  openandroidinstaller/views/install_view.py
  openandroidinstaller/views/select_view.py
  openandroidinstaller/views/step_view.py
Labels: enhancement

#198 a Doc folder to put documentation
  README.md
  doc/building_the_application_for_your_platform.md
  doc/how_to_contribute_your_own_installation_configurations.md
  doc/unlocking_the_bootloader.md
Labels: documentation

#243 Reworked the device request template as form
  .github/ISSUE_TEMPLATE/device-support-request.md
  .github/ISSUE_TEMPLATE/device-support-request.yaml
  openandroidinstaller/views/start_view.py
Labels: enhancement

#221 [SPLIT] Added optional device specific notes
  doc/how_to_contribute_your_own_installation_configurations.md
  openandroidinstaller/installer_config.py
  openandroidinstaller/views/select_view.py
Labels: enhancement

#226 [SPLIT] Add support for Mi439 (Redmi 7A & co.)
  README.md
  openandroidinstaller/assets/configs/Mi439.yaml
Labels: device

#255 Support galaxy s5
  README.md
  openandroidinstaller/assets/configs/klte.yaml
Labels: device

#256 Fix the bug with the progress bar percentages
  openandroidinstaller/views/install_addons_view.py
  openandroidinstaller/views/install_view.py
  openandroidinstaller/views/start_view.py
  openandroidinstaller/widgets.py
  tests/test_progress_bar.py
Labels: bug, enhancement
