Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2023-02, with the labels that each got.

#66 add griffin and cheesedump support
  README.md
  openandroidinstaller/assets/configs/OnePlus5.yaml
  openandroidinstaller/assets/configs/OnePlus5T.yaml
  openandroidinstaller/assets/configs/griffin.yaml
Labels: device

#36 Add preliminary config for Samsung Galaxy S III Neo (s3ve3g)
  README.md
  openandroidinstaller/assets/configs/s3ve3g.yaml
Labels: device

#75 Improve scripting component
  openandroidinstaller/openandroidinstaller.py
  openandroidinstaller/tooling.py
  openandroidinstaller/views/base.py
  openandroidinstaller/views/install_addons_view.py
  openandroidinstaller/views/install_view.py
  openandroidinstaller/views/step_view.py
  poetry.lock
  pyproject.toml
  tests/conftest.py
  tests/test_tooling.py
Labels: enhancement

#87 Greatlte support (first part)
  README.md
  openandroidinstaller/assets/configs/greatlte.yaml
Labels: device

#84 improve docs
  README.md
Labels: documentation, enhancement
