Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2023-09, with the labels that each got.

#290 Update Bootloader unlock info
  doc/unlocking_the_bootloader.md
Labels: documentation

#293 Docs update
  README.md
  doc/unlocking_the_bootloader.md
  docs/building_the_application_for_your_platform.md
  docs/how_to_contribute_your_own_installation_configurations.md
  docs/unlocking_the_bootloader.md
Labels: documentation

#246 Dev: flash additional partitions
  README.md
  docs/how_to_contribute_your_own_installation_configurations.md
  openandroidinstaller/app_state.py
  openandroidinstaller/assets/configs/Mi439.yaml
  openandroidinstaller/installer_config.py
  openandroidinstaller/tooling.py
  openandroidinstaller/utils.py
  openandroidinstaller/views/base.py
  openandroidinstaller/views/install_view.py
  openandroidinstaller/views/select_view.py
  openandroidinstaller/views/start_view.py
  openandroidinstaller/views/step_view.py
  poetry.lock
  pyproject.toml
  tests/test_progress_bar.py
Labels: enhancement

#223 [SPLIT] Add support for ginkgo (Xiaomi Redmi Note 8 / 8T)
  README.md
  openandroidinstaller/assets/configs/ginkgo.yaml
Labels: device

#225 [SPLIT] Add support for rosemary (Xiaomi Redmi Note 10S & co.)
  README.md
  openandroidinstaller/assets/configs/rosemary.yaml
Labels: device

#228 Add support for miatoll (Xiaomi Redmi Note 9 Pro / 9S ... Poco M2 Pro)
  README.md
  openandroidinstaller/assets/configs/miatoll.yaml
Labels: device

#235 Add support for raphael (Xiaomi Mi 9T Pro / Redmi K20 Pro)
  README.md
  openandroidinstaller/assets/configs/raphael.yaml
Labels: device

#271 Add support for vayu (Poco X3 Pro)
  README.md
  openandroidinstaller/assets/configs/vayu.yaml
Labels: device

#287 Add support for cupid (Xiaomi 12)
  README.md
  openandroidinstaller/assets/configs/cupid.yaml
Labels: device
