Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2023-10, with the labels that each got.

#306 [README] HTML header improvements
  README.md
Labels: documentation, enhancement, delayed

#310 Add support for begonia (Xiaomi Redmi Note 8 Pro)
  README.md
  openandroidinstaller/assets/configs/begonia.yaml
Labels: device

#208 Added new device code variant to `j7elte` & added TWRP link
  openandroidinstaller/assets/configs/j7elte.yaml
Labels: help wanted, device

#209 Added support for Samsung Galaxy J7 Prime
  README.md
  openandroidinstaller/assets/configs/on7xelte.yaml
Labels: device, needs testing, hacktoberfest-accepted

#207 Added support for Samsung Galaxy S4
  README.md
  openandroidinstaller/assets/configs/jfltexx.yaml
Labels: device, needs testing, hacktoberfest-accepted

#342 Add support for surya/karna (Poco X3 - X3 NFC)
  README.md
  openandroidinstaller/assets/configs/surya.yaml
Labels: device, hacktoberfest, hacktoberfest-accepted

#343 Add support for alioth (Redmi K40 / Mi 11X / Poco F3)
  README.md
  openandroidinstaller/assets/configs/alioth.yaml
Labels: device

#327 misc docs and minor config corrections/additions
  CODE_OF_CONDUCT.md
  README.md
  docs/building_the_application_for_your_platform.md
  docs/how_to_contribute_your_own_installation_configurations.md
  docs/unlocking_the_bootloader.md
  openandroidinstaller/assets/configs/Mi439.yaml
  openandroidinstaller/assets/configs/a7y17lte.yaml
  openandroidinstaller/assets/configs/begonia.yaml
  openandroidinstaller/assets/configs/cheeseburger.yaml
  openandroidinstaller/assets/configs/cupid.yaml
  openandroidinstaller/assets/configs/davinci.yaml
  openandroidinstaller/assets/configs/dumpling.yaml
  openandroidinstaller/assets/configs/fajita.yaml
  openandroidinstaller/assets/configs/garden.yaml
  openandroidinstaller/assets/configs/ginkgo.yaml
  openandroidinstaller/assets/configs/guacamole.yaml
  openandroidinstaller/assets/configs/guacamoleb.yaml
  openandroidinstaller/assets/configs/lavender.yaml
  openandroidinstaller/assets/configs/miatoll.yaml
  openandroidinstaller/assets/configs/raphael.yaml
  openandroidinstaller/assets/configs/rosemary.yaml
  openandroidinstaller/assets/configs/vayu.yaml
Labels: documentation, enhancement, hacktoberfest-accepted
