Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2024-01, with the labels that each got.

#399 Improve error message for loading images
  Makefile
  openandroidinstaller/utils.py
  openandroidinstaller/views/select_view.py
  openandroidinstaller/widgets.py
Labels: enhancement

#392 Add support for lancelot (Redmi 9 Poco M2)
  README.md
  openandroidinstaller/assets/configs/lancelot.yaml
Labels: device

#402 Improve resizing/scaling support
  openandroidinstaller/openandroidinstaller.py
  openandroidinstaller/views/base.py
  openandroidinstaller/views/requirements_view.py
  openandroidinstaller/views/start_view.py
Labels: bug, enhancement
