Repository openandroidinstaller-dev/openandroidinstaller, pull requests merged in 2025-02, with the labels that each got.

#642 fix python 3.12 support
  .pre-commit-config.yaml
  README.md
  poetry.lock
  resources/ekimia_logo.jpg
  scripts/lineageos-on-galaxy-a3.py
  scripts/lineageos-on-pixel3a.py
  scripts/lineageos-on-sony-xperia-z.py
Labels: enhancement

#656 Hello moto
  README.md
  openandroidinstaller/assets/configs/addison.yaml
  openandroidinstaller/assets/configs/ali.yaml
Labels: device

#501 configs: add billie support
  README.md
  openandroidinstaller/assets/configs/billie.yaml
Labels: device, needs testing

#488 Release v0.5.4-beta
  .pre-commit-config.yaml
  Makefile
  README.md
  openandroidinstaller/assets/configs/addison.yaml
  openandroidinstaller/assets/configs/ali.yaml
  openandroidinstaller/assets/configs/apollo.yaml
  openandroidinstaller/assets/configs/billie.yaml
  openandroidinstaller/assets/configs/removed/beyond0lte.yaml
  openandroidinstaller/assets/configs/removed/beyond1lte.yaml
  openandroidinstaller/assets/configs/removed/beyond2lte.yaml
  openandroidinstaller/assets/configs/violet.yaml
  openandroidinstaller/openandroidinstaller.py
  openandroidinstaller/views/addon_view.py
  openandroidinstaller/views/requirements_view.py
  openandroidinstaller/views/select_view.py
  openandroidinstaller/views/start_view.py
  poetry.lock
  pyproject.toml
  requirements.txt
  scripts/download-tools.py
  scripts/lineageos-on-galaxy-a3.py
  scripts/lineageos-on-pixel3a.py
  scripts/lineageos-on-sony-xperia-z.py
  tests/test_app.py
  tests/test_configs.py
Labels: enhancement
